### ISSUE TITLE
Valid event names

### ISSUE THREAD

**Issue by LuNoX** [PeterCat12/pysmash#16]
Since you only include WiiU events as valid events, every other type of event throws a ValidationError, including melee, which is way more popular than Sm4sh.
This also makes it impossible to look for custom events that aren't related to smash (like Rivals of Aether, Clash Royale, Guilty Crown, Street Fighter,...)

**Comment by PeterCat12** [comment]
Hey LuNoX. thanks for checking out the Lib. Yes, I had developed this for the Smash 4 scene initially since I am a part of the Smash 4 scene. I'll be updating this lib shortly (1-2 weeks? I'm pretty busy at the moment) to provide a param for an event name but feel free to fork it and implement it yourself, since it's very straight forward. The default param for event name is, indeed, Wii-U-Singles.

**Comment by PeterCat12** [comment]
Also, if you did implement it and PR it that would be dope :)

**Comment by LuNoX** [comment]
I just did it the ghetto way by adding the events I needed locally. It's not pretty but I figured until you get around to implementing it correctly, it'll do.

**Comment by PeterCat12** [comment]
Thanks for bringing it to my attention. I know this lib isn't in the most robust state at the moment but that is only due to lack of time on my part. If you want any additional features, or any other glaring bugs, etc, Keep on making issues. I will get around to them eventually :) 

Hopefully before the end of December it will be where I want to to be (functional tests, properly supporting doubles, other games, etc).

**Comment by PeterCat12** [comment]
Also, if it does end up satisfying whatever you use it for, consider staring the repo down the line (shameless self plug).

**Comment by LuNoX** [comment]
Sure, I will do that :)
Instead of validating the events you should probably just call https://api.smash.gg/tournament/[tourney name here]?expand[]=event and then look if the name pops up in the list

**Comment by PeterCat12** [comment]
👍 Good idea. Appreciate it.

**Comment by LuNoX** [comment]
Also, I just noticed that there is no function that does the above-mentioned query. Something like:

events = smash.tournament_show_events(tourney_name)

would be pretty neat.

**Comment by PeterCat12** [comment]
Would you mind opening up a separate issue for each thing you notice/feature you would like? That way I have a more concrete list of things to knock out rather than try to read through what might be a long(ish) thread haha

**Comment by LuNoX** [comment]
Sure.

**Comment by PeterCat12** [comment]
Appreciate it!

**Comment by PeterCat12** [comment]
Fixed in 2.0.0.  Note that this new update is probably a breaking change from the last version. See the updated documentation.
